apiVersion: apps/v1
kind: Deployment
metadata:
  name: "week3presentation-spring"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "week3presentation-app"
  template:
    metadata:
      labels:
        app: "week3presentation-app"
    spec:
      containers:
        - name: week3presentation-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9002
              protocol: TCP
